# Generated by Django 5.2.16 on 2026-09-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mls', '0055_listing_submission_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='precomproperty',
            name='featured_order',
            field=models.PositiveIntegerField(blank=True, help_text='Position among pinned projects (1 = first).', null=True),
        ),
        migrations.AddField(
            model_name='precomproperty',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Pin this project to the homepage pre-construction rail.'),
        ),
        migrations.AddField(
            model_name='property',
            name='featured_order',
            field=models.PositiveIntegerField(blank=True, help_text='Position in the Featured rail (1 = first). Blank sorts after numbered ones.', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='featured_until',
            field=models.DateTimeField(blank=True, help_text='Stop featuring after this time. Blank = until unticked.', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Pin this listing to the homepage Featured rail.'),
        ),
    ]
