# Generated by Django 5.2.16 on 2026-09-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mls', '0057_ai_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingsubmission',
            name='submitted_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listingsubmission',
            name='submitted_user_agent',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='listingviewevent',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listingviewevent',
            name='user_agent',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='propertyinquiry',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyinquiry',
            name='user_agent',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
